# Generated by Django 3.1 on 2025-11-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Paid', 'Paid'), ('Pending', 'Pending'), ('Unpaid', 'Unpaid')], default='Pending', max_length=10),
        ),
    ]
